project:
  type: website
  output-dir: docs

website:
  title: "IDS 702"
  sidebar:
    style: "docked"
    search: true
    background: "#1297e8"

format:
  html:
    theme: 
      light: [lux, custom.scss]
    css: styles.css
    toc: true

editor: visual

