project:
  type: website
  output-dir: docs

website:
  title: "IDS 702"
  sidebar:
    style: "docked"
    search: true
    background: "#1297e8"
    contents:
       - section:
         href: syllabus.qmd
         text: Syllabus
       - section: Course Materials
         contents:
          - section: "Unit 0: Bootcamp"
            contents:
            - href: materials/unit0/unit0b.qmd
          - section: "Unit 1: Statistics Fundamentals"
            contents:
            - href: materials/Unit1/IntroAndStudyDesign/Intro_ExperimentalDesign.qmd
            - href: materials/Unit1/IntrotoProbability/IntrotoProbability.qmd
            - href: materials/Unit1/Distributions/Distributions.qmd
            - href: materials/Unit1/Distributions/SamplingDistributions_CLT.qmd
            - href: materials/Unit1/Estimation/MLEstimation.qmd
            - href: materials/Unit1/ConfidenceIntervals/Bootstrap_CI.qmd
            - href: materials/Unit1/Inference/InferenceI.qmd
            - href: materials/Unit1/Inference/InferenceII.qmd
          - section: "Unit 2: Linear Regression"
            contents:
            - href: materials/Unit2/SLR.qmd
            - href: materials/Unit2/MLR.qmd
            - href: materials/Unit2/CategoricalInteraction.qmd
            - href: materials/Unit2/AssessingModels.qmd
            - href: materials/Unit2/Problems.qmd
            - href: materials/Unit2/ModelSelection.qmd
          - section: "Unit 3: Generalized Linear Models"
            contents:
            - href: materials/Unit3/Logistic Regression/IntrotoGLMs.qmd
            - href: materials/Unit3/Logistic Regression/LogisticEstimation.qmd
            - href: materials/Unit3/Logistic Regression/LogisticMetrics.qmd
            - href: materials/Unit3/Multinomial.qmd
            - href: materials/Unit3/Ordinal.qmd
            - href: materials/Unit3/Poisson.qmd
       - section:
         href: reflections.qmd
         text: Statistics Reflections
       - section: Homework
         contents:
         - href: homework/HW1.qmd
         - href: homework/HW2.qmd
         - href: homework/HW3.qmd
         - href: homework/HW4.qmd
         - href: homework/HW5.qmd
       - section:
         href: resources.qmd
         text: Resources
       - section:
         href: exam/Midterm.qmd
         text: Midterm
       - section: Project
         contents: 
         - href: project/proposal.qmd
         - href: project/reportandpres.qmd
         


format:
  html:
    theme: 
      light: [lux, custom.scss]
    css: styles.css
    toc: true

editor: visual

