project:
  type: website
  output-dir: docs

website:
  title: "IDS 702"
  sidebar:
    style: "docked"
    search: true
    background: "#1297e8"
    contents:
       - section:
         href: syllabus.qmd
         text: Syllabus
       - section: Course Materials
         contents:
          - section: "Unit 0: Bootcamp"
            contents:
            - href: materials/unit0/unit0b.qmd
          #- section: "Unit 1: Statistics Fundamentals"
           # contents:
            #- href: materials/Intro_ExperimentalDesign.qmd

format:
  html:
    theme: 
      light: [lux, custom.scss]
    css: styles.css
    toc: true

editor: visual

