---
title: "IDS 702: Data Modeling and Representation"
subtitle: "Duke University <br> Fall 2024"
---

Welcome to the IDS 702 course site!

## Course Overview

**Meeting times**: Tuesdays and Thursdays 3:05-4:20 PM, Gross Hall 330

<a>Instructor</a> <br/> Andrea Lane, PhD <br/> andrea.lane\@duke.edu <br/> Gross Hall 223 <br/> Office hours: Thurs 4:30-5:30 PM <br/> <br/> <a>Teaching Assistants</a> <br/> Revanth Ganga <br/> revanthchowdary.ganga\@duke.edu <br/> Office hours: Weds 12-1pm, Gross Hall 230N <br/> <br/> Rakeen Rouf <br/> rakeen.rouf\@duke.edu <br/> Office hours: Mon 3:30-4:30, Gross Hall 230N <br/> <br/> Jiayi Zhou <br/> jiayi.zhou\@duke.edu <br/> Office hours: Tues 12-1pm, Gross Hall 230N <br/> <br/>

## Schedule

Individual lecture topics are subject to change. The midterm date will not change.

+---------+---------------------------+--------------------------------+-------------------------+
| Week of | Tuesday content           | Thursday content               | Assignment due Sunday   |
+=========+===========================+================================+=========================+
| Aug 26  | Study Design              | Intro Probability              |                         |
+---------+---------------------------+--------------------------------+-------------------------+
| Sept 2  | Random variables &\       | Sampling Distributions & \     | Statistics Reflection 1 |
|         | Distributions             | Central Limit Theorem          |                         |
+---------+---------------------------+--------------------------------+-------------------------+
| Sept 9  | Estimation                | Confidence Intervals/Bootstrap | Homework 1              |
+---------+---------------------------+--------------------------------+-------------------------+
| Sept 16 | Inference I               | Inference II                   | Statistics Reflection 2 |
+---------+---------------------------+--------------------------------+-------------------------+
| Sept 23 | Intro to Regression       | Multiple Linear Regression     | Homework 2              |
+---------+---------------------------+--------------------------------+-------------------------+
| Sept 30 | Categorical Predictors, \ | Assessing Assumptions          | Statistics Reflection 3 |
|         | Interaction terms         |                                |                         |
+---------+---------------------------+--------------------------------+-------------------------+
| Oct 7   | Influential points & \    | Model Selection                | Homework 3              |
|         | Multicollinearity         |                                |                         |
+---------+---------------------------+--------------------------------+-------------------------+
| Oct 14  | Fall break - no class     | Exam review                    |                         |
+---------+---------------------------+--------------------------------+-------------------------+
| Oct 21  | Midterm Exam              | Intro to GLMs                  |                         |
+---------+---------------------------+--------------------------------+-------------------------+
| Oct 28  | Logistic Regression       | Assessing Logistic Models      | Statistics Reflection 4 |
+---------+---------------------------+--------------------------------+-------------------------+
| Nov 4   | Multinomial regression    | Ordinal regression             | Homework 4              |
+---------+---------------------------+--------------------------------+-------------------------+
| Nov 11  | Poisson regression        | Survival Analysis              | Project proposals       |
+---------+---------------------------+--------------------------------+-------------------------+
| Nov 18  | Missing Data              | Missing Data                   | Homework 5              |
+---------+---------------------------+--------------------------------+-------------------------+
| Nov 25  | Project work day          |                                |                         |
+---------+---------------------------+--------------------------------+-------------------------+
|         |                           |                                | Dec 15 5PM \            |
|         |                           |                                | Final projects due      |
+---------+---------------------------+--------------------------------+-------------------------+
