---
title: "10.31: Logistic Regression Assessment"
format: 
  html:
    link-external-newwindow: true
    link-external-icon: true
engine: knitr
webr: 
  show-startup-message: false
  show-header-message: false
  home-dir: '/home/r-user/'
  packages: ['ggplot2', 'dplyr']
filters:
  - webr
---

## Upcoming deadlines

-   Statistics Reflection 4: Sunday, Nov 3 11:59 PM
-   HW 4: Sunday, Nov 10 11:59 PM

**Reminder**: Class on Tuesday will be optional in observance of Election Day. We will not cover new material, but I will be available for questions.

## Learning Objectives

-   Identify which metrics from linear regression can be extended to logistic regression and why

-   Assess a logistic regression model with a confusion matrix

-   Explain what an ROC curve shows and generate one in R

## Class Prep

ISLR doesn't explicitly cover metrics for logistic regression, but section 4.4.2 describes some of the same concepts (confusion matrix, sensitivity and specificity, ROC curve). Start on page 148. We will discuss these concepts with an example in class.

Recordings for your reference:

[Logistic Regression Diagnostics](https://duke.zoom.us/rec/share/76FpESod4W3pX8MaD8wZJdqpfmPRP2-1UkaKLxt-YfNfaezgqlIxuu3Y7DvnGC5p.7Fw_NKJ-dTtZiaDQ?startTime=1696793841000)

[Assessing Logistic Models with Predictions](https://duke.zoom.us/rec/share/76FpESod4W3pX8MaD8wZJdqpfmPRP2-1UkaKLxt-YfNfaezgqlIxuu3Y7DvnGC5p.7Fw_NKJ-dTtZiaDQ?startTime=1696795225000)

Slides: [Diagnostics](IDS702_logisticmetrics.pdf); [Diagnostics with Predictions](IDS702_logisticmetricspredict.pdf)

## Class Materials

[Notes (qmd)](_LogisticAssessment.qmd)

Activity: ISLR Logistic Regression lab (4.7.1 and 4.7.2), and add the ROC curve
